name: Generate portfolio pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -la
          bash .github/scripts/generate.sh
          git config user.email "no-reply@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m"generate portfolio page"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git -f push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
