name: Generate portfolio pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v3
      - run: bash generate.sh
      - run: |
          git config user.email ${{ vars.EMAIL }}
          git config user.name ${{ vars.USERNAME }}
          git add .
          git commit -m"generate portfolio page"
          git push
